apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflared
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:+NAts3FrJzucC7N6JFA0bbKemFWFiWdMbQJT1fROrc9O6F6xcMer+Q5FC6rA6tLttjUKpTwbSvJ6r/pQEQHCNXth3WRwKDjkxtYVxq6GdQyAo8Tnnsx8Qb/HB/KrHWO2vIKd9GOZBqjLnjUJYnA++/YfFgNy7N56Lc2b6EsvgVxVthVhydZFPV7kCXPYUi/V2EsCIUHtGL0AxZpJMSUwuOvq3fFoFPIzOGTzyrav2T7PwuZ1EMlxMg==,iv:ngHAoxVx+PFOv87AWapT7+3NJCdYruhrCaPN5VXJtCE=,tag:HNkpCTeLee0fN62nwHYZeg==,type:str]
sops:
    age:
        - recipient: age1rkrq8j4fjt4vphs582esrqzj8esxx840xc6m7cc4ahzwcu52f3ysd62tje
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaGJHUDV2OGVEVW9NSDZH
            WXR6SkZuQS94SHk4cFBXQ0p4REx5S21Cc0NRCmd6UTBQMUlnbVhFamlzWjlLeXVK
            dGNzTUxicEQrRlQ3Yld5VWpLY2NBWVUKLS0tIDkrdSt0ai9GUXVtWWF2bUNrbUdr
            cVdzWnNOYTdjNlhNcldCYmwxY3d6bVkK3Nl55o8mfhluTPv+qFzNof5LUOMfieWR
            4a36xSMtPELEjaarrJ072Yb7U3Uo+ZPg1pIGUh+d5+L55pMMG6xdfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T21:22:56Z"
    mac: ENC[AES256_GCM,data:Di3zaYdYU+vd+QcXYh43tQiX+aCVjCq2tQUNUIiHp5MPrYicc725ujGgnOt72v5MnGYz8TW4r+JpyArm0OZNM7z9B31jwiS7v73jmOl2kXbzIKdtB4tffbehYR6lnkGeroPUrY1+lgCEFvhokoJwU/vQQrce8V3vHiG995tqZXQ=,iv:vlKJb3Ur7VFEmTtAbUOirVUtT9FdRCNBNBGI30Ca/Xc=,tag:hPkEhuL3Cq4/zSWfdnJEJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
