apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base
  - argocd-projects/infra-project.yaml
  - argocd-projects/portfolio-apps-project.yaml
  - apps/infra-apps/external-secrets-app.yaml
  - apps/infra-apps/cloudflared-app.yaml
  - apps/infra-apps/ingress-nginx-app.yaml
  - apps/infra-apps/monitoring-app.yaml
  - apps/business-argocd-apps/next-portfolio/prod-app.yaml
  - apps/business-argocd-apps/next-portfolio/stage-app.yaml
  - apps/business-argocd-apps/next-portfolio/dev-app.yaml