apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-stage-app
  namespace: stage
spec:
  project: portfolio-apps
  source:
    repoURL: https://github.com/nishanau/infra-gitops.git
    path: azure/business-apps/next-portfolio/manifests/overlays/stage
    targetRevision: stage
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
