apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: doppler-secret-store
    kind: SecretStore
  target:
    name: cloudflared-credentials
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: tunnel-token
      remoteRef:
        key: AZURE_CLOUDFLARED_TUNNEL_TOKEN
