apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: doppler-secret-store
  namespace: cloudflared
spec:
  provider:
    doppler:
      project: baremetal-k8s-project
      config: prd
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-auth
            key: dopplerToken
